### ISSUE TITLE
Hacktoberfest2019: Add your awesome automation scripts

### ISSUE THREAD

**Issue by adityaarakeri** [adityaarakeri/super-scripts#1]
[HACKTOBERFEST 2019](https://hacktoberfest.digitalocean.com/) is HERE !!! 
🎉🎉🎉🎉🎉
![hacktoberfest2019](https://raw.githubusercontent.com/adityaarakeri/super-scripts/master/hactoberfest2019.png)

GOAL:
The goal of this issue is to submit as many  😎Awesome 🎉automation scripts you can which has made your life easier

RULES:
1. The scripts should be placed inside its own folder
2. Each script can have a readme
3. Script related files can be stored inside its folder
4. Please name your scripts appropriately
5. Scripts can be in any language
6. Any level of scripts are welcome
7. Please do not add binary files, PR will be rejected

```
Happy
HACKTOBERFEST 2019
```

**Comment by Venkat230407** [comment]
I will try on this.. Assign this to me

**Comment by adityaarakeri** [comment]
@Venkat230407 i cant assign it to you, this is an open issue and can be worked on by any one wanting to contribute to this repo

**Comment by coolsonu39** [comment]
I created #53 please have a look :)

**Comment by giantthinker** [comment]
Hello, cannot push to your repo.

**Comment by FARVE14** [comment]
Hi @adityaarakeri , I'd like to contribute to this. Thanks.

**Comment by adityaarakeri** [comment]
> Hello, cannot push to your repo.

fork the repo and submit a PR

**Comment by adityaarakeri** [comment]
Closing this since we have 2020
