### ISSUE TITLE
Hacktoberfest 2020: Add some Awesome automation scripts

### ISSUE THREAD

**Issue by adityaarakeri** [adityaarakeri/super-scripts#111]
# Hackotoberfest 2020 🎉 🎉 🎉

https://hacktoberfest.digitalocean.com/

![Hacktoberfest2020](https://raw.githubusercontent.com/adityaarakeri/super-scripts/master/hacktoberfest2020.png)

### GOAL
The goal of this issue is to submit as many 😎 Awesome 🎉automation scripts you can which has made your life easier

### RULES
- The scripts should be placed inside its own folder
- Each script can have a readme
- Script related files can be stored inside its folder
- Please name your scripts appropriately
- Scripts can be in any language
- Any level of scripts are welcome
- Please do not add binary files, PR will be rejected

**Comment by Apoorve73** [comment]
I can work on adding some cool, selenium webdriver based automations, and SMTP mail sending(with added features).

**Comment by murilopereirame** [comment]
I can work on a data generator written in C#

**Comment by KwanJunWen** [comment]
I can add a script that search a folder for go executable and build `go` binary.

**Comment by binay1999** [comment]
I can add a script which automatically generates graphs showing the status of Coronavirus in India.

**Comment by jacobggman** [comment]
I can write a script that generates MD5 hash for file in Python

**Comment by rohan2734** [comment]
can anyone explain me what is automation of scripts,  and what skills do we require for that, i would like to work on this.

**Comment by Apoorve73** [comment]
@rohan2734 , An automation script is any program that prevents any intervention by user and performs sone task by itself(thus saving pur time)
For example: Writing a python script to submit your assignmemt on Google Classroom.
When script runs(in this case), It will simply open your browser, enter your Google Classroom url, then login using the credentials you given in the code, and then submit your work in the desired classroom.

**Comment by rohan2734** [comment]
@Apoorve73  thanks for the information bro, can we do that with javascript? or what is the best language ? for the automation script?

**Comment by Apoorve73** [comment]
No worries! :) Any language will.work. Well! Most often, Python is chosen for that due to its vast library support.

**Comment by rohan2734** [comment]
@Apoorve73  oh actually i wanted this type of thing in my react-native-app, can we do that automation in python and can we link somehow with the app? like i mean can python and js be combined? asnwer is  no right?

**Comment by Apoorve73** [comment]
Ofcourse, you can combine JS with Python using Django or Flask.
https://developer.okta.com/blog/2018/12/20/crud-app-with-python-flask-react
Check this out!

**Comment by rohan2734** [comment]
@Apoorve73  no I mean ,my current backend is nodejs,database is mongodb, and frontend is react-native, If i just want to add python automation script, will it work,? the code may not compile right?

**Comment by Apoorve73** [comment]
@rohan2734 , you need to create a FLASK API for connecting to your backend, and use that to run a python script on some event that might be handled by JS

**Comment by rohan2734** [comment]
@Apoorve73 oh ok, well can i maintain two backends then , one with FLASK API for just python automation script and one backend with nodejs for other remaining tasks?

**Comment by Apoorve73** [comment]
Yes!. ofcourse, you can.deploy your Flask application on some other server, and use the API for requests.

**Comment by rohan2734** [comment]
@Apoorve73 thanks bro, before this , i thought this is something done by learning AI ,and it was going to be tough.is this like an AI, if it is used for large tasks.? answer is no right?

**Comment by Apoorve73** [comment]
Ah! Happens man! 
Check this https://youtu.be/s7wmiS2mSXY
It includes all your answers!

**Comment by rohan2734** [comment]
@Apoorve73 you have given an example right for the google classroom right? can you provide links for that?

**Comment by Apoorve73** [comment]
It is just an idea of how to build one.
Though, Google Classroom API is already available for this purpose.

**Comment by rohan2734** [comment]
> It is just an idea of how to build one.
> Though, Google Classroom API is already available for this purpose.

ok

**Comment by Apoorve73** [comment]
> > It is just an idea of how to build one.
> > Though, Google Classroom API is already available for this purpose.
> 
> ok, we can aslo use selenium right?,for automation scripts?

Yes! You can!

**Comment by rohan2734** [comment]
> > > It is just an idea of how to build one.
> > > Though, Google Classroom API is already available for this purpose.
> > 
> > 
> > ok, we can aslo use selenium right?,for automation scripts?
> 
> Yes! You can!

but whenever I search automation of scripts with selenium, it shows selenium automation of scripts for "TESTING",
I dont want to test anything, i just want to run automation script, is it same as testing?

**Comment by Apoorve73** [comment]
Next time when you search, enter the query as follows:
" Automation using Selenium Webdriver "

**Comment by rohan2734** [comment]
> Next time when you search, enter the query as follows:
> " Automation using Selenium Webdriver "

ok i got few results thanks.

**Comment by rohan2734** [comment]
so i can even write a medium automation script and push right?, it doesnt need to be a  very good one right?

**Comment by Apoorve73** [comment]
Oops! Are you a magician?
I am.working on it for a project I am mentoring! Haha

**Comment by RealRadOne** [comment]
I can add a script that opens your emails and other favourite websites every 4 hours.

**Comment by rohan2734** [comment]
@RealRadOne  can you share some links, so that i can aslo learn and do this task.

**Comment by RealRadOne** [comment]
> @RealRadOne can you share some links, so that i can aslo learn and do this task.

@rohan2734 You can check this out:https://github.com/RealRadOne/Crony-Bash :D

**Comment by rohan2734** [comment]
@RealRadOne  the language is shell? idk that, i asked for tutorials . can you send them?

**Comment by HappyMercury** [comment]
I have written a basic script in python that adds all music files of type .mp3 from downloads folder to a separate music folder on the desktop. Can i add that?

**Comment by harjotsingh1999** [comment]
Hi, I have written an automation script that logs in to your LinkedIn profile and scrapes your followers and adds their names to an excel sheet. A new sheet is made if the code is run for the first time, and for the rest, updates are made to the same excel sheet. New followers are marked in green, while those lost are marked in red in the previous column(if it exists). It works using selenium and gecko webdriver. Can I add that?

**Comment by rohan2734** [comment]
@harjotsingh1999  hey can you send me some links to refer them?

**Comment by harjotsingh1999** [comment]
> @harjotsingh1999 hey can you send me some links to refer them?

By links you mean learning resources or the code?

**Comment by rohan2734** [comment]
@harjotsingh1999  i mean tutorials for learning them.

**Comment by harjotsingh1999** [comment]
> @harjotsingh1999 i mean tutorials for learning them.

You can refer automatetheboringstuff.com . That's what I used to learn.

**Comment by rohan2734** [comment]
@harjotsingh1999  oh thanks , but can you tell me any resource for learning these things in js?

**Comment by gioboa** [comment]
I can add a js script that produce a file (placeholder) only if your project files are changed.

**Comment by rohan2734** [comment]
i can add a  script, where you can send connection request and message to linkedin users .

**Comment by SiriusKoan** [comment]
I want to add a tool that can help you download youtube audio automatically with pytube and pyqt, can I do this?

**Comment by tusharnankani** [comment]
Adding a Python Auto Draw Script

**Comment by tusharnankani** [comment]
Adding a text to speech and vice versa script.

**Comment by tusharnankani** [comment]
Adding Tic Tac Toe with AI

**Comment by JohnWesleyK** [comment]
I can work on a program that calculates wages accurately using python.

**Comment by Jstnlee1997** [comment]
Hi, may I add a script that tracks your "Most Liked", "Most Viewed" and "Subscribers" and determines the top 5 channels of each category and automatically opens up a window whenever one of them posts a new video.

**Comment by mahendrarathore1742** [comment]
can i add some more files

**Comment by Nightsmore** [comment]
Created a PR for #162

**Comment by Flamer17** [comment]
Hey, I can Create a python script to generate morse code(both text and audio) and decode morse code code as well

**Comment by kanishk307** [comment]
I have worked on a an automation script to take screenshots, save webpages and save pdfs using selenium. Can I add?

**Comment by ArpitaGanatra** [comment]
@adityaarakeri  I have created a pull request for Instagram profile pic downloader in python.  #182
