### ISSUE TITLE
Add the "hacktoberfest" topic to the repository

### ISSUE THREAD

**Issue by Arnau-Ninerola** [adityaarakeri/super-scripts#155]
In order for the pull requests to count as valid you should have the "hacktoberfest" topic in your repository. 

Like this: https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif

**Comment by VAJRESH** [comment]
yes please.

**Comment by adityaarakeri** [comment]
Thank you for this.
it's updated now.

**Comment by VAJRESH** [comment]
Please accept my PR and add hacktober fest label to it.
