### ISSUE TITLE
Organize the repo for cleaner look and a beautify the readme

### ISSUE THREAD

**Issue by adityaarakeri** [adityaarakeri/super-scripts#178]
Currently the repo is a complete mess with a wide variety of naming conventions and folder structures
1. reorganize the scripts in a different folder in the root called `scripts`
2. the script folder names are quite inconsistent for example: `first-name` ,`First_name`, `First_Name` so rename them to `First_Middle_Name` format
3. update the `readme` to point to the scripts in the new structure
4. make a more elegant `readme`

Note: This issue will be awarded to person commenting first and would be given a week to finish the task.

**Comment by sonylomo** [comment]
Hey @adityaarakeri, what do you mean by making a more elegant readme?

**Comment by mscreation28** [comment]
Hey @adityaarakeri, I would like to work on this... Please assign it to me..!

**Comment by adityaarakeri** [comment]
@sonylomo update the readme to make it look good and have all the existing relevant information needed. Do you want to work on this issue, since you commented first?

**Comment by sanjus-robotic-studio** [comment]
@adityaarakeri can you assign me

**Comment by sonylomo** [comment]
Yes I would like to work on it 😁

**Comment by adityaarakeri** [comment]
@sonylomo its assigned to you, please send a PR before Oct 25.

**Comment by ramkrishn123** [comment]
I would like to work on it .
